/*
* EJERCICIO:
 * - Crea un comentario en el código y coloca la URL del sitio web oficial del
 *   lenguaje de programación que has seleccionado.
 * - Representa las diferentes sintaxis que existen de crear comentarios
 *   en el lenguaje (en una línea, varias...).
 * - Crea una variable (y una constante si el lenguaje lo soporta).
 * - Crea variables representando todos los tipos de datos primitivos
 *   del lenguaje (cadenas de texto, enteros, booleanos...).
 * - Imprime por terminal el texto: "¡Hola, [y el nombre de tu lenguaje]!"
 *
/*
https://developer.mozilla.org/es/docs/Web/JavaScript

/*
ccc
COMENTARIO
ccc
*/
let a;
const b = 1;

let c = "string";
let num = 2;
let boolean = true;
let u;
let bi = 2^52 -1;
let s = Symbol("HHAY")
console.log(`¡Hola, JavaScript!`);
console.log(u)
console.log(s)
console.log(bi)
